// Generated by scripts/gen-bootstrap.ts — do not edit by hand.
// Regenerate with `npm run db:bootstrap` after changing db/schema.ts.

export const BOOTSTRAP_DDL: string[] = [
  "CREATE TABLE IF NOT EXISTS `channels` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`name` text NOT NULL,\n\t`handle` text,\n\t`accent` text NOT NULL,\n\t`mission` text NOT NULL,\n\t`audience` text NOT NULL,\n\t`voice` text NOT NULL,\n\t`formats` text NOT NULL,\n\t`never_do` text NOT NULL,\n\t`cta` text,\n\t`script_style` text NOT NULL,\n\t`cadence_per_week` integer NOT NULL,\n\t`target_depth` integer NOT NULL,\n\t`record_days` text NOT NULL,\n\t`sort_order` integer DEFAULT 0 NOT NULL\n);",
  "CREATE TABLE IF NOT EXISTS `clips` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`channel_id` text NOT NULL,\n\t`source_url` text NOT NULL,\n\t`premise` text,\n\t`source` text,\n\t`status` text DEFAULT 'queued' NOT NULL,\n\t`used_by_item_id` text,\n\t`added_at` text NOT NULL,\n\tFOREIGN KEY (`channel_id`) REFERENCES `channels`(`id`) ON UPDATE no action ON DELETE no action\n);",
  "CREATE TABLE IF NOT EXISTS `items` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`channel_id` text NOT NULL,\n\t`title` text NOT NULL,\n\t`format_key` text,\n\t`status` text DEFAULT 'idea' NOT NULL,\n\t`premise` text,\n\t`hook` text,\n\t`script` text,\n\t`shot_notes` text,\n\t`caption` text,\n\t`hashtags` text,\n\t`record_on` text,\n\t`post_on` text,\n\t`post_time` text,\n\t`asset_url` text,\n\t`post_url` text,\n\t`clip_id` text,\n\t`notes` text,\n\t`archived` integer DEFAULT false NOT NULL,\n\t`created_at` text NOT NULL,\n\t`updated_at` text NOT NULL,\n\tFOREIGN KEY (`channel_id`) REFERENCES `channels`(`id`) ON UPDATE no action ON DELETE no action\n);",
  "CREATE TABLE IF NOT EXISTS `performance` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`item_id` text NOT NULL,\n\t`views` integer,\n\t`likes` integer,\n\t`comments` integer,\n\t`shares` integer,\n\t`saves` integer,\n\t`follows` integer,\n\t`recorded_at` text NOT NULL,\n\tFOREIGN KEY (`item_id`) REFERENCES `items`(`id`) ON UPDATE no action ON DELETE no action\n);",
  "CREATE TABLE IF NOT EXISTS `videos` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`channel_id` text NOT NULL,\n\t`item_id` text,\n\t`filename` text NOT NULL,\n\t`source_url` text NOT NULL,\n\t`size_bytes` integer,\n\t`status` text DEFAULT 'uploaded' NOT NULL,\n\t`transcript_text` text,\n\t`words` text,\n\t`plan` text,\n\t`render_id` text,\n\t`render_url` text,\n\t`error` text,\n\t`created_at` text NOT NULL,\n\t`updated_at` text NOT NULL,\n\tFOREIGN KEY (`channel_id`) REFERENCES `channels`(`id`) ON UPDATE no action ON DELETE no action\n);",
  "ALTER TABLE `channels` ADD `logo` text;",
  "ALTER TABLE `items` ADD `loop_line` text;",
  "ALTER TABLE `items` ADD `estimated_seconds` integer;",
  "ALTER TABLE `videos` ADD `transcript_id` text;",
  "ALTER TABLE `videos` ADD `caption` text;",
  "ALTER TABLE `videos` ADD `caption_alt` text;",
  "ALTER TABLE `videos` ADD `hashtags` text;",
  "ALTER TABLE `videos` ADD `hashtag_note` text;",
  "ALTER TABLE `items` ADD `from_user` integer DEFAULT false NOT NULL;",
  "ALTER TABLE `channels` ADD `news_driven` integer DEFAULT false NOT NULL;",
  "ALTER TABLE `channels` ADD `product_notes` text;"
];
