import { readFileSync, readdirSync, writeFileSync } from "node:fs";

const files = readdirSync("drizzle").filter((f) => f.endsWith(".sql")).sort();

const statements = files
  .flatMap((f) => readFileSync(`drizzle/${f}`, "utf8").split("--> statement-breakpoint"))
  .map((s) => s.trim())
  .filter(Boolean)
  // Boot runs on every cold start, so every statement has to be a no-op the second time.
  .map((s) =>
    s
      .replace(/^CREATE TABLE /i, "CREATE TABLE IF NOT EXISTS ")
      .replace(/^CREATE (UNIQUE )?INDEX /i, "CREATE $1INDEX IF NOT EXISTS "),
  );

const out = `// Generated by scripts/gen-bootstrap.ts — do not edit by hand.
// Regenerate with \`npm run db:bootstrap\` after changing db/schema.ts.

export const BOOTSTRAP_DDL: string[] = ${JSON.stringify(statements, null, 2)};
`;

writeFileSync("db/bootstrap.ts", out);
console.log(`Wrote db/bootstrap.ts (${statements.length} statements).`);
process.exit(0);
